from rag.agents.base import AgentResult
from rag.agents.citation_gap_agent import CitationGapDetectionAgent
from rag.agents.future_trend_agent import FutureTrendPredictionAgent
from rag.agents.hypothesis_agent import HypothesisGenerationAgent
from rag.agents.literature_review_agent import LiteratureReviewAgent
from rag.agents.novelty_agent import NoveltyAnalysisAgent
from rag.agents.qa_agent import ResearchQAAgent
from rag.agents.section_drafting_agent import SectionDraftingAgent
from rag.agents.summarization_agent import ResearchSummarizationAgent

